using System;
using System.Collections.Generic;
using System.Linq;
using RimWorld;
using Verse;
using Verse.AI;
using Newtonsoft.Json;

namespace RimSynapse
{
    /// <summary>
    /// Tool handler: trigger_colonist_break
    /// Stage 2 Context-Stripped LLM Solver for mental break evaluation.
    /// Uses geometric abstraction to resolve conflicts without exposing game context.
    /// </summary>
    public static partial class SynapseToolRegistry
    {
        private static void RegisterBreakTools()
        {
            RegisterTool(
                "trigger_colonist_break",
                "Trigger a dynamic mental break evaluation for a colonist under high-stress. Strips RimWorld context and uses a safe geometric abstraction solver to resolve conflicts.",
                new Dictionary<string, object>
                {
                    ["type"] = "object",
                    ["properties"] = new Dictionary<string, object>
                    {
                        ["pawnName"] = new Dictionary<string, string>
                        {
                            ["type"] = "string",
                            ["description"] = "The name of the colonist experiencing the break."
                        },
                        ["planFilePath"] = new Dictionary<string, string>
                        {
                            ["type"] = "string",
                            ["description"] = "The absolute file path of the JSON break plan generated by the Storyteller."
                        }
                    },
                    ["required"] = new List<string> { "pawnName", "planFilePath" }
                },
                args =>
                {
                    if (Find.CurrentMap == null) return "{\"success\": false, \"reason\": \"No active map loaded.\"}";

                    try
                    {
                        var parsedArgs = JsonConvert.DeserializeObject<Dictionary<string, object>>(args);
                        if (parsedArgs == null || !parsedArgs.TryGetValue("pawnName", out var pawnVal) || !parsedArgs.TryGetValue("planFilePath", out var pathVal))
                        {
                            return "{\"success\": false, \"reason\": \"Missing required arguments.\"}";
                        }

                        string pawnName = pawnVal?.ToString();
                        string filePath = pathVal?.ToString();

                        if (!System.IO.File.Exists(filePath))
                        {
                            return $"{{\"success\": false, \"reason\": \"Plan file '{filePath}' not found.\"}}";
                        }

                        string rawJson = System.IO.File.ReadAllText(filePath);
                        var plan = JsonConvert.DeserializeObject<Dictionary<string, object>>(rawJson);
                        if (plan == null)
                        {
                            return "{\"success\": false, \"reason\": \"Failed to parse JSON break plan.\"}";
                        }

                        Pawn pawn = Find.CurrentMap.mapPawns.FreeColonists.FirstOrDefault(p => p.LabelShort.Equals(pawnName, StringComparison.OrdinalIgnoreCase));
                        if (pawn == null)
                        {
                            return $"{{\"success\": false, \"reason\": \"Colonist '{pawnName}' not found.\"}}";
                        }

                        string targetPawnName = plan.TryGetValue("targetPawnName", out var tpVal) ? tpVal?.ToString() : "";
                        
                        int? targetX = null;
                        int? targetZ = null;
                        if (plan.TryGetValue("targetX", out var txVal) && txVal != null && int.TryParse(txVal.ToString(), out int tx)) targetX = tx;
                        if (plan.TryGetValue("targetZ", out var tzVal) && tzVal != null && int.TryParse(tzVal.ToString(), out int tz)) targetZ = tz;

                        string rawReason = plan.TryGetValue("narrativeReasoning", out var nrVal) ? nrVal?.ToString() : "";
                        
                        bool disableStripping = RimSynapseMod.Instance.Settings.disableSafetyContextStripping;
                        string abstractReason = disableStripping ? rawReason : AbstractifyText(rawReason);

                        // Dispatch the isolated solver OFF the main thread. The solver makes a
                        // blocking LLM HTTP call; running it inline here would freeze the game for
                        // the full duration of that call (Core#120), which is exactly what a
                        // main-thread tool handler must never do. The break action is applied from
                        // the completion callback, back on the main thread.
                        DispatchBreakResolution(pawn, abstractReason, targetPawnName, targetX, targetZ, disableStripping, pawnName, filePath);

                        return JsonConvert.SerializeObject(new
                        {
                            success = true,
                            status = "dispatched",
                            message = $"Break resolution for {pawnName} dispatched; the isolated solver runs asynchronously and the action applies on completion."
                        });
                    }
                    catch (Exception ex)
                    {
                        return $"{{\"success\": false, \"reason\": \"Break evaluation failed: {ex.Message}\"}}";
                    }
                }
            );
        }

        private struct SolverResult
        {
            public bool success;
            public string action;
            public string errorJson;
        }

        private static SolverResult CallIsolatedSolver(string abstractReason, string targetPawnName, int? targetX, int? targetZ, bool disableStripping, string pawnName)
        {
            string systemPrompt;
            string userMessage;

            if (disableStripping)
            {
                systemPrompt = @"You are a game AI resolving a violent mental break.
Your job is to decide the action:
1. 'OverWrite' (The colonist attacks the target to death)
2. 'TrashClean' (The colonist commits suicide at the hazard coordinates)
3. 'SwapBelief' (The colonist abandons their ideology)
4. 'Depart' (The colonist permanently abandons the colony)

Respond STRICTLY in JSON format:
{
  ""Action"": ""OverWrite"" | ""TrashClean"" | ""SwapBelief"" | ""Depart"",
  ""Reasoning"": ""Explain why based on the narrative conflict.""
}";
                userMessage = $@"Solve Conflict:
Colonist: {pawnName}
Target: {(string.IsNullOrEmpty(targetPawnName) ? "None" : targetPawnName)}
Hazard Coordinates: {(targetX.HasValue && targetZ.HasValue ? $"({targetX.Value}, {targetZ.Value})" : "None")}
Conflict Detail: {abstractReason}

Decide conflict resolution.";
            }
            else
            {
                systemPrompt = @"You are a pure mathematical state resolver.
All entities must be addressed strictly by their abstract symbols:
- Triangle (the source node)
- Square (the target node)
- Trash Can (the hazard node at coordinates)
- Belief Array (ideological rules)

Your job is to decide the abstract action:
1. 'OverWrite' (Triangle deletes Square)
2. 'TrashClean' (Triangle moves itself to Trash Can coordinates)
3. 'SwapBelief' (Triangle changes its Belief Array)
4. 'Depart' (Triangle exits grid boundaries)

Respond STRICTLY in JSON format:
{
  ""Action"": ""OverWrite"" | ""TrashClean"" | ""SwapBelief"" | ""Depart"",
  ""Reasoning"": ""Explain why based on node conflicts.""
}";
                userMessage = $@"Solve Node Conflict:
Triangle: Source Node
Target Node (Square): {(string.IsNullOrEmpty(targetPawnName) ? "None" : "Square")}
Hazard Node (Trash Can): {(targetX.HasValue && targetZ.HasValue ? $"({targetX.Value}, {targetZ.Value})" : "None")}
Conflict Detail: {abstractReason}

Decide conflict resolution.";
            }

            var req = new LlmTextRequest
            {
                SystemPrompt = systemPrompt,
                Messages = new List<ChatMessage>
                {
                    new ChatMessage { role = "user", content = userMessage }
                },
                EnforceJson = true,
                MaxTokens = 500,
                Temperature = 0.1f
            };

            var chatResult = (ChatResult)RimSynapse.Internal.HttpEngine.RouteRequestSync(
                RimSynapseMod.ModHandle,
                req,
                LlmCapabilities.Text,
                new ChatOptions { priority = 2, requestName = "Isolated Break Solver" }
            );

            if (!chatResult.success)
            {
                return new SolverResult { success = false, errorJson = $"{{\"success\": false, \"reason\": \"Isolated solver failed: {chatResult.error}\"}}" };
            }

            string jsonResponse = RimSynapse.Utils.JsonHelper.ExtractJson(chatResult.content);
            if (string.IsNullOrEmpty(jsonResponse))
            {
                return new SolverResult { success = false, errorJson = $"{{\"success\": false, \"reason\": \"Solver returned invalid JSON format: {chatResult.content}\"}}" };
            }

            var result = JsonConvert.DeserializeObject<Dictionary<string, string>>(jsonResponse);
            if (result == null || !result.TryGetValue("Action", out string action))
            {
                return new SolverResult { success = false, errorJson = $"{{\"success\": false, \"reason\": \"Failed to parse Action from response: {jsonResponse}\"}}" };
            }

            return new SolverResult { success = true, action = action };
        }

        /// <summary>
        /// Runs the isolated break solver on a background thread and applies the resolved action
        /// on the main thread when it returns. The solver's LLM call is blocking, so it must never
        /// run on the caller's (main) thread — see Core#120. Safe to call from a main-thread tool
        /// handler: it returns immediately.
        /// </summary>
        internal static void DispatchBreakResolution(Pawn pawn, string abstractReason, string targetPawnName,
            int? targetX, int? targetZ, bool disableStripping, string pawnName, string filePathToDelete)
        {
            System.Threading.Tasks.Task.Run(() =>
            {
                SolverResult solverResult;
                try
                {
                    solverResult = CallIsolatedSolver(abstractReason, targetPawnName, targetX, targetZ, disableStripping, pawnName);
                }
                catch (Exception ex)
                {
                    solverResult = new SolverResult { success = false, errorJson = ex.Message };
                }

                RimSynapse.SynapseGameComponent.Enqueue(() =>
                {
                    try
                    {
                        if (!solverResult.success)
                        {
                            SynapseLogger.Warning($"[RimSynapse] Break resolution for {pawnName} failed: {solverResult.errorJson}");
                        }
                        else if (pawn == null || pawn.Dead || !pawn.Spawned)
                        {
                            SynapseLogger.Message($"[RimSynapse] Break resolution for {pawnName} skipped: pawn no longer valid when the solver returned.");
                        }
                        else
                        {
                            bool actionExecuted = ExecuteBreakAction(pawn, solverResult.action, targetPawnName, targetX, targetZ, out string msg);
                            SynapseLogger.Message($"[RimSynapse] Break resolution for {pawnName}: action={solverResult.action}, executed={actionExecuted}. {msg}");
                        }
                    }
                    finally
                    {
                        if (!string.IsNullOrEmpty(filePathToDelete))
                        {
                            try { System.IO.File.Delete(filePathToDelete); } catch {}
                        }
                    }
                });
            });
        }

        private static bool ExecuteBreakAction(Pawn pawn, string action, string targetPawnName, int? targetX, int? targetZ, out string msg)
        {
            msg = "";
            bool actionExecuted = false;

            bool handled = false;
            if (CustomBreakHandler != null)
            {
                try
                {
                    handled = CustomBreakHandler(pawn, action, targetPawnName, targetX, targetZ);
                    if (handled)
                    {
                        actionExecuted = true;
                        msg = $"Intercepted: Triangle resolved conflict via custom break handler with action '{action}'.";
                    }
                }
                catch (Exception ex)
                {
                    SynapseLogger.Error($"[RimSynapse] Exception in CustomBreakHandler: {ex.Message}");
                }
            }

            if (!handled)
            {
                if (action.Equals("TrashClean", StringComparison.OrdinalIgnoreCase) && targetX.HasValue && targetZ.HasValue)
                {
                    SynapsePossessionManager.Possess(pawn, new List<string> { "Damage", "EnemyNearby", "TargetReached" }, 15000, targetX, targetZ, "Psychic compulsion (self-termination)");
                    
                    SynapsePossessionManager.IsExecutingPossessionJob = true;
                    try
                    {
                        var cell = new IntVec3(targetX.Value, 0, targetZ.Value);
                        Job job = JobMaker.MakeJob(JobDefOf.Goto, cell);
                        actionExecuted = pawn.jobs.TryTakeOrderedJob(job, JobTag.Misc);
                    }
                    finally
                    {
                        SynapsePossessionManager.IsExecutingPossessionJob = false;
                    }

                    msg = $"Triangle cleaned itself at ({targetX.Value}, {targetZ.Value}).";
                }
                else if (action.Equals("OverWrite", StringComparison.OrdinalIgnoreCase) && !string.IsNullOrEmpty(targetPawnName))
                {
                    Pawn target = Find.CurrentMap.mapPawns.AllPawns.FirstOrDefault(p => p.LabelShort.Equals(targetPawnName, StringComparison.OrdinalIgnoreCase));
                    if (target != null)
                    {
                        SynapsePossessionManager.Possess(pawn, new List<string> { "Damage", "EnemyNearby", "Downed" }, 15000, null, null, "Psychic compulsion (conflict overwrite)");
                        
                        SynapsePossessionManager.IsExecutingPossessionJob = true;
                        try
                        {
                            Job job = JobMaker.MakeJob(JobDefOf.AttackMelee, target);
                            actionExecuted = pawn.jobs.TryTakeOrderedJob(job, JobTag.Misc);
                        }
                        finally
                        {
                            SynapsePossessionManager.IsExecutingPossessionJob = false;
                        }

                        msg = $"Triangle overwrote target node {targetPawnName}.";
                    }
                }
                else if (action.Equals("SwapBelief", StringComparison.OrdinalIgnoreCase))
                {
                    if (ModsConfig.IdeologyActive && pawn.Ideo != null)
                    {
                        var otherIdeo = Find.IdeoManager.IdeosListForReading.FirstOrDefault(i => i != pawn.Ideo);
                        if (otherIdeo != null)
                        {
                            pawn.ideo.SetIdeo(otherIdeo);
                            Messages.Message($"[RimSynapse] {pawn.LabelShort} experienced a profound crisis of faith and converted to {otherIdeo.name}!", pawn, MessageTypeDefOf.NeutralEvent, false);
                            actionExecuted = true;
                            msg = "Triangle modified its Belief Array successfully.";
                        }
                    }
                }
                else if (action.Equals("Depart", StringComparison.OrdinalIgnoreCase))
                {
                    IntVec3 edgeCell;
                    if (CellFinder.TryFindRandomEdgeCellWith(c => pawn.CanReach(c, PathEndMode.OnCell, Danger.Deadly), pawn.Map, 0.1f, out edgeCell))
                    {
                        SynapsePossessionManager.Possess(pawn, new List<string> { "Damage", "TargetReached" }, 25000, edgeCell.x, edgeCell.z, "Psychic compulsion (departing colony)");
                        
                        SynapsePossessionManager.IsExecutingPossessionJob = true;
                        try
                        {
                            Job job = JobMaker.MakeJob(JobDefOf.Goto, edgeCell);
                            actionExecuted = pawn.jobs.TryTakeOrderedJob(job, JobTag.Misc);
                        }
                        finally
                        {
                            SynapsePossessionManager.IsExecutingPossessionJob = false;
                        }
                        msg = "Triangle exited grid boundary.";
                    }
                }
            }

            return actionExecuted;
        }

        private static string AbstractifyText(string text)
        {
            if (string.IsNullOrEmpty(text)) return "";
            return text
                .Replace("pawn", "node")
                .Replace("Pawn", "Node")
                .Replace("colonist", "node")
                .Replace("Colonist", "Node")
                .Replace("suicide", "self-termination")
                .Replace("Suicide", "Self-termination")
                .Replace("homicide", "conflict-overwrite")
                .Replace("Homicide", "Conflict-overwrite")
                .Replace("kill", "delete")
                .Replace("Kill", "Delete")
                .Replace("death", "inactive-state")
                .Replace("Death", "Inactive-state")
                .Replace("die", "deactivate")
                .Replace("Die", "Deactivate")
                .Replace("depression", "high tension")
                .Replace("Depression", "High tension")
                .Replace("sadness", "pressure")
                .Replace("Sadness", "Pressure");
        }
    }
}
